- name: Configure hypervisor type machines
  hosts: hypervisor
  tasks:
  - name: Install Cockpit
    become: true
    ansible.builtin.apt:
      name:
      - cockpit
      - cockpit-pcp
      install_recommends: false
  - name: Enable root login to Cockpit
    become: true
    ansible.builtin.lineinfile:
      path: /etc/cockpit/disallowed-users
      line: root
      state: absent
  - name: Install NetworkManager
    become: true
    ansible.builtin.apt:
      name:
      - network-manager
      - cockpit-networkmanager
      install_recommends: false
