- name: Configure hypervisor type machines
  hosts: hypervisor
  tasks:
  - name: Install Cockpit
    become: true
    ansible.builtin.apt:
      name:
      - cockpit
      - cockpit-pcp
      install_recommends: false
  - name: Enable root login to Cockpit
    become: true
    ansible.builtin.lineinfile:
      path: /etc/cockpit/disallowed-users
      line: root
      state: absent
  - name: Install NetworkManager
    become: true
    ansible.builtin.apt:
      name:
      - network-manager
      - cockpit-networkmanager
      install_recommends: false
  - name: Empty /etc/network/interfaces
    become: true
    ansible.builtin.copy:
      dest: /etc/network/interfaces
      content: |
        # Emptied out via Ansible during configuration
  - name: Configure lanbr0
    become: true
    ansible.builtin.nmcli:
      conn_name: lanbr0
      type: bridge
      stp: false
      mac: "{{ ansible_facts[ main_interface ]['macaddress'] }}"
      state: present
  - name: Configure lanbr0-port0
    ansible.builtin.nmcli:
      conn_name: lanbr0-port0
      ifname: "{{ main_interface }}"
      type: bridge-slave
      master: lanbr0
      state: present
  - name: Install Podman
    ansible.builtin.apt:
      name:
      - podman
      - cockpit-podman
  - name: Configure unprivileged containers
    become: true
    ansible.builtin.lineinfile:
      path: "{{ item }}"
      line: root:100000:65536
    loop:
      - /etc/subuid
      - /etc/subgid
  - name: Install libvirt
    become: true
    ansible.builtin.apt:
      name:
      - qemu-system
      - qemu-utils
      - libvirt-daemon-system
      - libvirt-clients
      - virtinst
      - ovmf
      - cockpit-machines
      install_recommends: false
  - name: Install NFS Server
    become: true
    ansible.builtin.apt:
      name:
      - nfs-common
      - nfs-kernel-server
      install_recommends: false
